//******************************************************************************
// Copyright (c) 2018, The Regents of the University of California (Regents).
// All Rights Reserved. See LICENSE for license details.
//------------------------------------------------------------------------------
#include "edge_wrapper.h"
#include <string.h>
#include "verifier/report.h"
/* Really all of this file should be autogenerated, that will happen
   eventually. */

#define OCALL_LOAN_SHM 8

void edge_init(Keystone::Enclave *enclave)
{
	printf("[JADU] edge_init called!\n");
    enclave->registerOcallDispatch(incoming_call_dispatch);
    register_call(OCALL_LOAN_SHM, loan_shm_wrapper);

}

void loan_shm_wrapper(void *buffer, size_t _shared_len)
{
	printf("[JADU] loan_shm_wrapper called!\n");
    uintptr_t _shared_start = (uintptr_t)buffer;
    /* For now we assume the call struct is at the front of the shared
     * buffer. This will have to change to allow nested calls. */
    struct edge_call *edge_call = (struct edge_call *)buffer;

    uintptr_t call_args;
    size_t arg_len;
    if (edge_call_args_ptr(edge_call, &call_args, &arg_len, _shared_start, _shared_len) != 0)
    {
        edge_call->return_data.call_status = CALL_STATUS_BAD_OFFSET;
        return;
    }

    unsigned long ret_val;
    shm_t shm;
    shm = loan_shm(*(int *)call_args);

    uintptr_t data_section = edge_call_data_ptr(_shared_start, _shared_len);
    memcpy((void *)data_section, &shm, sizeof(shm_t));

    if (edge_call_setup_ret(
            edge_call, (void *)data_section, sizeof(shm_t), _shared_start, _shared_len))
    {
        edge_call->return_data.call_status = CALL_STATUS_BAD_PTR;
    }
    else
    {
        edge_call->return_data.call_status = CALL_STATUS_OK;
    }

    return;
}
